Ely_blog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from Ely_blog import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('account/', include('account.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register_view, name='register'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('list', views.article_list, name='list'),
    path('search', views.searcher, name='search'),
    path('contact_us', views.contact_us, name='contact_us'),
    path('message', views.MessageView.as_view(), name='message'),
    path('article_details/<slug:slug>', views.ArticleDetailView.as_view(), name='article_details'),
    path('message_list', views.MessageListView.as_view(), name='message_list'),
    path('message/edit/<int:pk>', views.UpdateMessageView.as_view(), name='message_edit'),
    path('message/delete/<int:pk>', views.DeleteMessageView.as_view(), name='message_delete'),
    path('like/<slug:slug>/<int:pk>', views.like, name='like'),

]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='main'),
]

templates/includes/footer.html
{% load static %}
<div class="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="footer-contact">
                    <span class="footer-title">چگونه با ما در تماس باشید</span>
                    <ul>
                        <li><a href="#" title="041311111111" data-toggle="tooltip"><i class="fa fa-phone"></i></a></li>
                        <li><a href="#" title="تبریز " data-toggle="tooltip"><i class="fa fa-map-marker"></i></a></li>
                        <li><a href="#" title="info@seo90.ir" data-toggle="tooltip"><i class="fa fa-envelope-o"></i></a>
                        </li>
                        <li><a href="#" title="09352604271" data-toggle="tooltip"><i class="fa fa-mobile"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-8">
                <div class="footer-random-posts">
                    <span class="footer-title">شاید این مطالب را بپسندید</span>
                    <div class="col-md-6">
                        <a href="#">
                            <div class="footer-random-posts-body">
                                <figure>
                                    <img src="{% static 'img/blog/blog4.jpg' %}" alt="">
                                </figure>
                                <h4>دوچرخه سواری و استقامت</h4>
                                <span><i class="fa fa-calendar-o"></i>98/8/7</span>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-6">
                        <a href="#">
                            <div class="footer-random-posts-body">
                                <figure>
                                    <img src="{% static 'img/blog/blog7.jpg' %}" alt="">
                                </figure>
                                <h4>ورزش و سلامتی </h4>
                                <span><i class="fa fa-calendar-o"></i>98/8/7</span>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-6">
                        <a href="#">
                            <div class="footer-random-posts-body">
                                <figure>
                                    <img src="{% static 'img/blog/blog7.jpg' %}" alt="">
                                </figure>
                                <h4>آیا تنیس قدرت بدنی بالایی نیاز دارد؟</h4>
                                <span><i class="fa fa-calendar-o"></i>98/8/7</span>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-6">
                        <a href="#">
                            <div class="footer-random-posts-body">
                                <figure>
                                    <img src="{% static 'img/blog/blog4.jpg' %}" alt="">
                                </figure>
                                <h4>طبیعت گردی در روح انسان چه تاثیری دارد ؟</h4>
                                <span><i class="fa fa-calendar-o"></i>98/8/7</span>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <br><br><br>
        <center>
            <p>حقوق انتشار برای وب سایت محفوظ است - قالب seo90.ir</p>
        </center>
    </div>
</div>

templates/includes/footer_references.html
{% load static %}
<script type="text/javascript" src="{% static 'js/jquery.1.8.3.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
<script type="text/javascript" src="{% static 'js/wow.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.particleground.js' %}"></script>
<script type="text/javascript" src="{% static 'js/for_ajax.js' %}"></script>
<script>
    jQuery("[data-toggle='tooltip']").tooltip();
    jQuery('.footer').particleground({
        dotColor: '#515151',
        lineColor: '#515151'
    });
</script>

templates/includes/head_references.html
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, maximum-scale=1">
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/font-awesome.css' %}" rel="stylesheet" type="text/css">
<link href='https://cdn.fontcdn.ir/Font/Persian/Vazir/Vazir.css' rel='stylesheet' type='text/css'>
<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<!--[if IE]>
      <style type="text/css">.pie {behavior:url({% static 'PIE.htc' %});}</style>
      <![endif]-->
<!--[if lt IE 9]>
      <script src="{% static 'js/respond-1.1.0.min.js' %}"></script>
      <script src="{% static 'js/html5shiv.js' %}"></script>
      <script src="{% static 'js/html5element.js' %}"></script>
      <![endif]-->

templates/includes/header.html
{% load static %}
{% load my_template_tags %}
<div class="main-menu">
    <div class="container">
        <ul>
            <li><a href="{% url 'home:main' %}">صفحه اصلی</a></li>
            <li><a href="{% url 'blog:list' %}">مقالات</a></li>
            <li><a href="{% url 'blog:contact_us' %}">تماس با ما</a></li>
            <li><a href="#">درباره</a></li>
            <li><a href="">{% current_time "%Y-%m-%d %I:%M %p" %}</a></li>
        </ul>
    </div>
</div>
<div class="top-section">
    <div class="container">
        <div class="row">
            <div class="col-md-2">
<<<<<<< HEAD
                <li>
=======
                <li class="nav-item">
>>>>>>> master
                    {% if request.user.is_authenticated %}
                        <div class="d-flex">
                            {% if request.user.first_name %}
                                {% if user.profile.user_image %}
<<<<<<< HEAD
                                    <span><img src="{{ user.profile.user_image.url }}" width="35" height="35"
=======
                                    <span><img src="{{ user.profile.user_image.url }}" width="50" height="50"
>>>>>>> master
                                               style="border-radius: 100%" alt=""></span>
                                {% else %}
                                    <span><img src="{% static 'images/icons/profile_user.png' %}" width="35"
                                               height="35"
                                               style="border-radius: 100%" alt=""></span>
                                {% endif %}
                                <a class="nav-link"
                                   href="">{{ request.user.first_name }} {{ request.user.last_name }} </a>
                            {% else %}
                                <a class="nav-link"
                                   href="">{{ request.user.username }} </a>
                            {% endif %}

                            <a href="{% url 'account:logout' %}"><span class="badge badge-danger mt-2">logout</span></a>
                        </div>
                    {% else %}
                        <div class="d-flex">
                            <a class="nav-link" href="{% url 'account:login' %}">Login</a><span
                                class="mt-2">/</span>
                            <a class="nav-link" href="{% url 'account:register' %}">Register</a>
                        </div>
                    {% endif %}
                </li>
            </div>
            <div class="col-md-5">
                <form method="get" action="{% url 'blog:search' %}" class="search-form">
                    <input type="text" name="search" placeholder="جستجو کنید ...">
                    <button type="submit"><i class="fa fa-search"></i></button>
                </form>
            </div>
            <div class="col-md-5">
                <div class="index-h1">
                    <h1>وبلاگ مقالات</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<br>
<center>
    <p style="font-size: 16px;color: #444;">آخرین مطالب وبلاگ</p>
</center>
<hr>

templates/includes/sidebar.html
{% load static %}
<div class="col-md-3">
    <div class="sidebar">
        <div class="sidebar-text">
            <p>"به وبلاگ ما خوش آمدید! اینجا مکانی است که ما در مورد موضوعات مختلفی از جمله فناوری، سلامتی، هنر و فرهنگ،
                تاریخ و سبک زندگی صحبت می‌کنیم. امیدواریم که با خواندن مطالب ما لحظات خوبی را سپری کنید و اطلاعات جدیدی
                را به دست بیاورید. منتظر نظرات شما هستیم و امیدواریم که اینجا برای شما تجربه‌ای لذت‌بخش باشد."</p>
        </div>
        <div class="sidebar-social">
            <ul>
                <li>
                    <a href="https://t.me/Elyasshavikloo" class="telegram"><i class="fa fa-send"></i>دنبال کردن در تلگرام</a>
                </li>
                <li>
                    <a href="https://github.com/ElyasShavikloo"><i class="fa fa-github"></i>گیت هاب</a>
                </li>
                <li>
                    <a href="https://www.linkedin.com/in/elyas-shavikloo-b82751284/"><i class="fa fa-linkedin"></i>لینکدین</a>
                </li>
                <li>
                    <a href="https://stackoverflow.com/users/22477434/elyas-shavikloo"><i class="fa fa-stack-overflow"></i>استک اور فلو</a>
                </li>
                <li>
                    <a href="https://www.instagram.com/elyasshavikloo7" class="instagram"><i class="fa fa-instagram"></i>پیج اینستاگرام </a>
                </li>
            </ul>
        </div>
        <div class="category-sidebar">
            <span><i class="fa fa-bookmark"></i>مقالات اخیر</span>
            <ul>
                {% for item in recent_article %}
                    <li>
                        <span>
                            <a href="{{ item.get_absolut_url }}"> {{ item.title }}
                            <p>{{ item.body|truncatewords:30 }}</p>
                            </a>
                            <div>
                                <img src="{{ item.image.url }}" alt="img">
                            </div>
                        </span>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <br><br>
        <div class="category-sidebar">
            <span><i class="fa fa-bookmark"></i>دسته بندی ها</span>
            <ul>
                {% for category in categories %}
                    <li><span class="text-primary"><a href="">{{ category.title }}</a></span></li>
                {% endfor %}
            </ul>
        </div>
        <div class="category-sidebar ads-sidebar">
            <span><i class="fa fa-slack"></i>تبلیغات</span>
            <ul>
                <li>
                    <a href="#">
                        <figure>
                            <img src="{% static 'img/ads/ads1.jpg' %}" alt="">
                            <figcaption></figcaption>
                        </figure>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>