Ely_blog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from Ely_blog import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('account/', include('account.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('list', views.article_list, name='list'),
    path('search', views.searcher, name='search'),
    path('contact_us', views.contact_us, name='contact_us'),
    path('message', views.MessageView.as_view(), name='message'),
    path('article_details/<slug:slug>', views.ArticleDetailView.as_view(), name='article_details'),
    path('message_list', views.MessageListView.as_view(), name='message_list'),
    path('message/edit/<int:pk>', views.UpdateMessageView.as_view(), name='message_edit'),
    path('message/delete/<int:pk>', views.DeleteMessageView.as_view(), name='message_delete'),
    path('like/<slug:slug>/<int:pk>', views.like, name='like'),

]

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.html import format_html
from django.utils.text import slugify


class Category(models.Model):
    title = models.CharField(max_length=17, verbose_name="عنوان")
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'


class Article(models.Model):
    title = models.CharField(max_length=50, verbose_name="عنوان")
    category = models.ManyToManyField(Category, related_name='articles', verbose_name="دسته بندی")
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="نویسنده")
    image = models.ImageField(upload_to='articles/images', blank=True, null=True, verbose_name="تصویر")
    created = models.DateTimeField(auto_now_add=True, verbose_name="ایجاد شده")
    updated = models.DateTimeField(auto_now=True, verbose_name="به روز رسانی شده")
    body = models.TextField(verbose_name="بدنه")
    status = models.BooleanField(default=True, verbose_name="وضعیت")
    slug = models.SlugField(null=True, blank=True, unique=True, verbose_name="اسلاگ")

    class Meta:
        verbose_name = 'مقاله'
        verbose_name_plural = 'مقالات'

    def save(
            self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        self.slug = slugify(self.title)
        super(Article, self).save()

    def show_image(self):
        if self.image:
            return format_html(f'<img src="{self.image.url}" width="47px" height="37px">')
        else:
            return format_html('<h3 style="color: red">بدون تصویر</h3>')

    show_image.short_description = ' تصویر'

    def get_absolut_url(self):
        return reverse('blog:article_details', kwargs={'slug': self.slug})

    def __str__(self):
        return f'{self.title} {self.body[:30]}'

    def update_counter(self):
        pass


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments', verbose_name="مقاله")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments', verbose_name="کاربر")
    parent_id = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='replies')
    body = models.TextField(verbose_name="بدنه")
    created = models.DateTimeField(auto_now_add=True, verbose_name="ایجاد شده")

    def __str__(self):
        return self.body[:37]

    class Meta:
        verbose_name = 'نظر'
        verbose_name_plural = 'نظرات'


class Message(models.Model):
    title = models.CharField(max_length=107, verbose_name="عنوان")
    text = models.TextField(verbose_name="پیام")
    email = models.EmailField( verbose_name="ایمیل")
    age = models.IntegerField(default=0, verbose_name="سن")
    created = models.DateTimeField(auto_now_add=True, null=True, verbose_name="ایجاد شده")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'پیام'
        verbose_name_plural = 'پیام ها'


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='likes', verbose_name='کاربر')
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='likes', verbose_name='مقاله')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')

    def __str__(self):
        return f'{self.user.username} - {self.article.title}'

    class Meta:
        verbose_name = "لایک"
        verbose_name_plural = "لایک ها"
        ordering = ("-created_at",)

blog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from blog.models import Message


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = '__all__'
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'موضوع چیست؟',
            }),
            'text': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': "چه چیزی می خواهید بگویید؟"
            })
        }

blog/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from .forms import MessageForm
from .models import Article, Comment, Category, Message, Like
from django.core.paginator import Paginator
from django.views.generic.base import View, TemplateView, RedirectView
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy
from .mixins import CustomLoginRequiredView


def article_list(request):
    articles = Article.objects.all().order_by('-created')
    page_number = request.GET.get('page')
    paginator = Paginator(articles, 3)
    object_list = paginator.get_page(page_number)

    return render(request, 'blog/list.html', context={'articles': object_list})


def searcher(request):
    search = request.GET.get('search')
    articles = Article.objects.filter(title__icontains=search)
    page_number = request.GET.get('page')
    paginator = Paginator(articles, 3)
    object_list = paginator.get_page(page_number)
    return render(request, 'blog/list.html', context={'articles': object_list})


def contact_us(request):
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            instance = form.save()
            instance.age += 1
            return redirect('home:main')

    else:
        form = MessageForm()
    return render(request, 'blog/message_form.html', {'form': form})


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'blog/details.html'

    def __init__(self, **kwargs):
        super().__init__()
        self.object = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.comments.filter(article__slug=self.object.slug, user_id=self.request.user.id).exists():
            context['commented'] = True

        elif self.request.user.likes.filter(article__slug=self.object.slug, user_id=self.request.user.id).exists():
            context['is_liked'] = True
        else:
            context['is_liked'] = False

        return context


def like(request, slug, pk):
    if request.user.is_authenticated:
        try:
            like = Like.objects.get(article__slug=slug, user_id=request.user.id)
            like.delete()
            return JsonResponse({'response': 'unliked'})

        except:
            like = Like.objects.create(article_id=pk, user_id=request.user.id)
            return JsonResponse({'response': 'liked'})


def comment(request, slug, pk):
    if request.user.is_authenticated:
        comment = Comment.objects.create(article_id=pk, user_id=request.user.id)
        comment.save()
        return JsonResponse({'response': 'commented'})


# class ArticleListView(ListView):
#     model = Article
#     template_name = 'blog/list.html'
#     paginate_by = 3


class MessageView(CreateView):
    model = Message
    fields = '__all__'
    success_url = reverse_lazy('home:main')

    # this project template's is awful, and I can't do or run some things like this function
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['titles'] = Message.objects.all()
    #
    #     return context


class MessageListView(CustomLoginRequiredView, ListView):
    model = Message
    template_name = 'blog/messages_list.html'


class UpdateMessageView(UpdateView):
    model = Message
    fields = '__all__'
    success_url = reverse_lazy('blog:message_list')


class DeleteMessageView(DeleteView):
    model = Message
    success_url = reverse_lazy('blog:message_list')

blog/templates/blog/details.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ article.title }}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            {% include 'includes/sidebar.html' %}
            <div class="col-md-9">
                <div class="col-md-12">
                    <div class="single-content">
                        <div class="single-img">
                            <img src="{{ article.image.url }}" alt="img">
                        </div>
                        <div class="single-meta">
                            <ul>
                                <li><a href="#" title="{{ article.created }}" data-toggle="tooltip"><i
                                        class="fa fa-calendar-o"></i></a></li>
                                <li><a href="#" title="{{ article.updated }}" data-toggle="tooltip"><i
                                        class="fa fa-reply"></i></a></li>
                                <li><a href="#" title="{{ article.author }}" data-toggle="tooltip"><i
                                        class="fa fa-user-o"></i></a></li>
                                <li><a href="#" title="اخبار ، ورزش" data-toggle="tooltip"><i
                                        class="fa fa-bars"></i></a>
                                </li>
                                <li><a href="#" title="اشتراک در توئیتر" data-toggle="tooltip"><i
                                        class="fa fa-twitter"></i></a>
                                </li>
                                <li><a href="#" title="اشتراک در فیس بوک" data-toggle="tooltip"><i
                                        class="fa fa-facebook"></i></a></li>
                                <li><a href="#" title="اشتراک در لینکدین" data-toggle="tooltip"><i
                                        class="fa fa-linkedin"></i></a></li>
                            </ul>
                        </div>
                        <div class="single-title">
                            <h1>{{ article.title }}</h1>
                            <h2>{{ article.author }}</h2>
                            <h6>{{ article.created }}</h6>
                        </div>
                        <p>{{ article.body }}</p>
                        <br>


                        <div class="col-6">
                            <ul class="post-tags">
                                {% if is_liked %}
                                    <li><span type="submit" onclick="like('{{ article.slug }}', '{{ article.id }}')"
                                    ><i
                                            id="like"
                                            style="font-size: 20px; color: red"
                                            class="fa fa-heart"></i><span
                                            id="count">{{ article.likes.all.count }}</span>
                                    </span></li>
                                {% else %}
                                    <li><span type="submit" onclick="like('{{ article.slug }}', '{{ article.id }}')"
                                    ><i
                                            id="like"
                                            style="font-size: 20px; color: red"
                                            class="fa fa-heart-o"></i><span
                                            id="count">{{ article.likes.all.count }}</span>
                                    </span></li>
                                {% endif %}
                            </ul>
                        </div>
                        <hr>

                        <div class="content">
                            <ul>
                                {% for comment in article.comments.all %}
                                    {% if comment.parent_id == None %}
                                        <li>
                                            <div class="author-decor">
                                                {% if comment.user.profile.user_image %}
                                                    <img src="{{ comment.user.profile.user_image.url }}" alt="img">
                                                {% else %}
                                                    <img src="{% static 'img/icons/profile_user.png' %}" alt="img">
                                                {% endif %}
                                            </div>
                                            <div class="align-content-sm-center">
                                                <h4>{{ comment.user }}<span>{{ comment.created }}</span>
                                                </h4>
                                                <p>{{ comment.body }}</p>
                                                <button onclick="set_value({{ comment.id }})"
                                                        class="btn btn-primary">reply
                                                </button>
                                            </div>
                                        </li>
                                        {% for reply in comment.replies.all %}
                                            <li class="fa-mail-reply">
                                                <div class="author-thumb">
                                                    {% if reply.user.profile.user_image %}
                                                        <img src="{{ reply.user.profile.user_image.url }}"
                                                             alt="">
                                                    {% else %}
                                                        <img src="{% static 'img/icons/profile_user.png' %}"
                                                             alt="">
                                                    {% endif %}
                                                </div>
                                                <div class="right-content">
                                                    <h4>{{ reply.user }}<span>{{ reply.created }}</span>
                                                    </h4>
                                                    <p>{{ reply.body }}</p>
                                                </div>
                                            </li>
                                        {% endfor %}
                                    {% endif %}
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="comment">
                            <span><i class="fa fa-comments"></i>نظری برای این مطلب بنویسید</span>
                            <form id="comment" action="" method="post">
                                {% csrf_token %}
                                <div class="form-group col-md-12">
                                    <div class="row">
                                        <input type="hidden" id="parent_id" name="parent_id" value="">
                                        <fieldset>
                                                                                            <textarea
                                                                                                    class="form-control"
                                                                                                    name="body"
                                                                                                    id="body"
                                                                                                    placeholder="متن نظر"
                                                                                                    rows="7"></textarea>
                                        </fieldset>
                                    </div>
                                    <div class="form-group col-md-12">
                                        <button class="btn btn-default" type="submit">ارسال نظر</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="comments-note">
                            نظرات این مطلب
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>

        function set_value(id) {
            document.getElementById('parent_id').value = id;
            window.location.href = '#body'
        }

    </script>
{% endblock %}

blog/templates/blog/edit_message.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{% endblock %}
Contact Us
{% block content %}
    <center>
        <p style="font-size: 16px;color: #444;">Contact Us</p>
    </center>
    <div class="content">
        <form id="contact" action="" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-lg-12">
                    <div>
                        {{ form }}
                    </div>
                </div>
                <div class="col-lg-12">
                    <fieldset>
                        <button type="submit" id="form-submit" class="main-button">
                            Submit
                        </button>
                    </fieldset>
                </div>
            </div>
        </form>
        <div>
            {% for item in titles %}
                <p>{{ item.title }}</p>
            {% endfor %}
        </div>
    </div>
{% endblock %}

blog/templates/blog/list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Article list
{% endblock %}

{% block content %}
        <p style="font-size: 16px;color: #444;">مقالات</p>
    <hr>
    <div class="container">
        <div class="row">
            {% for article in articles %}
                <div class="col-md-3">
                    <a href="{{ article.get_absolut_url }}">
                        <div class="post-content">
                            <figure>
                                <img src="{{ article.image.url }}" alt="img">
                                <figcaption class="hover-fig">
                                    <i class="fa fa-plus"></i>
                                </figcaption>
                                <figcaption class="date-fig">
                                    <span>{{ article.created }}</span>
                                    <i class="fa fa-date"></i>
                                </figcaption>
                            </figure>
                            <div>
                                <h3>{{ article.title }}</h3>
                                <h4>{{ article.author }}</h4>
                            </div>
                            <p>{{ article.body|truncatechars:137 | safe }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
        <br>
        <div class="col-lg-12">
            {% if articles.has_other_pages %}
                <ul class="pagination">
                    {% if articles.has_previous %}
                        <li><a href="?page={{ articles.previous_page_number }}"><i class="fa fa-angle-double-left"></i></a>
                        </li>
                    {% endif %}


                    {% for item in articles.paginator.page_range %}
                        {% if articles.number == item %}
                            <li class="active"><a href="?page=
                                    {{ item }}{% if request.GET.search %}&q={{ request.GET.search }}{% endif %}">{{ item }}</a>
                            </li>
                        {% else %}
                            <li><a href="?page=
                                    {{ item }}{% if request.GET.search %}&q={{ request.GET.search }}{% endif %}">{{ item }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}


                    {% if articles.has_next %}
                        <li><a href="?page=
                                {{ articles.next_page_number }}{% if request.GET.search %}&q={{ request.GET.search }}{% endif %}"><i
                                class="fa fa-angle-double-right"></i></a></li>
                    {% endif %}
                </ul>
            {% endif %}
        </div>
    </div>
    <br><br>
{% endblock %}

blog/templates/blog/message_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>
</body>
</html>

blog/templates/blog/message_form.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{% endblock %}
Contact Us
{% block content %}
    <center>
        <p style="font-size: 16px;color: #444;">تماس با ما</p>
    </center>
    <div class="content" dir="ltr">
        <form id="contact" action="" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-lg-12">
                    <div dir="auto">
                        {{ form }}
                    </div>
                </div>
                <div class="col-lg-12">
                    <fieldset>
                        <button type="submit" id="form-submit" class="main-button">
                            Submit
                        </button>
                    </fieldset>
                </div>
            </div>
        </form>
        <div>
            {% for item in titles %}
                <p>{{ item.title }}</p>
            {% endfor %}
        </div>
    </div>
{% endblock %}

blog/templates/blog/messages_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{% endblock %}
Messages List
{% block content %}
    <center>
        <p style="font-size: 16px;color: #444;">Messages List</p>
    </center>
    <div class="content" dir="ltr" style="text-align: center">
        {% for item in message_list %}
            <p>{{ item.title }} - {{ item.email }} - {{ item.age }} <span class="btn btn-primary"><a
                    href="{% url 'blog:message_edit' item.id %}" style="color: black">Edit</a></span>
                <span class="btn btn-danger"><a href="{% url 'blog:message_delete' item.id %}" style="color: black">Delete</a></span></p>
            <hr>
        {% endfor %}
    </div>

{% endblock %}